version: '3.7'
services:
  data-archive-frontend:
    image: data-archive-frontend
    container_name: data-archive-frontend
    build: 
      context: ${DATA_ARCHIVE_FRONTEND_BASE_DIR}
      dockerfile: Dockerfile.prod
    volumes: 
      - data-archive-frontend-build:/opt/data-archive-frontend/build
    restart: on-failure

  data-archive-backend:
    image: data-archive-backend
    container_name: data-archive-backend
    build: 
      context: ${DATA_ARCHIVE_BACKEND_BASE_DIR}
      dockerfile: Dockerfile.prod
    volumes: 
      - ${DATA_REQUEST_BASE_DIR}
    ports: 
      - ${DATA_ARCHIVE_BACKEND_PORT}:4001
    restart: on-failure
  
  nginx:
    image: data-archive-nginx
    container_name: data-archive-nginx
    build: 
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    volumes:
      - data-archive-frontend-build:/usr/share/nginx/html/build
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: on-failure

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email saltastroops@saao.ac.za --agree-tos --no-eff-email -d ssda.saao.ac.za -d www.ssda.saao.ac.za
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes: 
  data-archive-frontend-build:
